global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/recording_rules.yml
  - /etc/prometheus/alerting_rules.yml

scrape_configs:
  - job_name: 'araquem-api'
    static_configs:
      - targets: ['api:8000']
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
