apiVersion: 1

datasources:
  - name: Prometheus
    uid: grafana
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 5s

  - name: Araquem JSON API
    uid: jsonapi
    type: grafana-json-datasource
    access: proxy
    url: http://api:8000
    jsonData:
      timeout: 600
