apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Araquem JSON API
    uid: jsonapi
    type: marcusolsson-json-datasource
    access: proxy
    url: http://api:8000
    jsonData:
      timeout: 600
